{
 "title": "Cassandra Datasource Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "loc",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Query Editor Demo",
   "type": "timeseries",
   "description": "This panel demonstrates the powerful Query Editor of Apache Cassandra Datasource for Grafana",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "{{ sensor_id }}:{{ location }}",
     "columnId": " ",
     "columnTime": " ",
     "columnValue": " ",
     "target": "SELECT sensor_id, temperature, registered_at, location FROM test.test WHERE sensor_id IN (99051fe9-6a9c-46c2-b949-38ef78858dd1, 99051fe9-6a9c-46c2-b949-38ef78858dd0) AND registered_at > $__timeFrom and registered_at < $__timeTo",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Query Configurator Demo",
   "type": "graph",
   "description": "This panel is configured using Apache Cassandra Datasource and Query Configurator",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ID:{{ sensor_id }}",
     "columnId": "sensor_id",
     "columnTime": "registered_at",
     "columnValue": "temperature",
     "keyspace": "test",
     "table": "test",
     "target": "select timestamp, value from keyspace.table where id=123e4567;",
     "type": "timeserie",
     "valueId": "99051fe9-6a9c-46c2-b949-38ef78858dd0, 99051fe9-6a9c-46c2-b949-38ef78858dd1"
    }
   ]
  },
  {
   "title": "Query By Variable Demo",
   "type": "timeseries",
   "description": "This panel demonstrates the powerful Query Editor of Apache Cassandra Datasource for Grafana",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "{{ sensor_id }}:{{ location }}",
     "columnId": " ",
     "columnTime": " ",
     "columnValue": " ",
     "target": "SELECT sensor_id, temperature, registered_at, location FROM test.test WHERE sensor_id = ${loc} AND registered_at > $__timeFrom and registered_at < $__timeTo",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Table Editor Demo",
   "type": "table",
   "description": "This panel demonstrates the table mode of Apache Cassandra Datasource for Grafana",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "columnId": " ",
     "columnTime": " ",
     "columnValue": " ",
     "target": "SELECT sensor_id, temperature, registered_at, location FROM test.test WHERE sensor_id IN (99051fe9-6a9c-46c2-b949-38ef78858dd1, 99051fe9-6a9c-46c2-b949-38ef78858dd0) AND registered_at > $__timeFrom and registered_at < $__timeTo PER PARTITION LIMIT 1",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Table Configurator Demo",
   "type": "table",
   "description": "This panel demonstrates the table mode of Apache Cassandra Datasource for Grafana",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "columnId": "sensor_id",
     "columnTime": "registered_at",
     "columnValue": "temperature",
     "keyspace": "test",
     "table": "test",
     "valueId": "99051fe9-6a9c-46c2-b949-38ef78858dd0, 99051fe9-6a9c-46c2-b949-38ef78858dd1"
    }
   ]
  }
 ]
}