FROM grafana/grafana:7.3.6

RUN wget -c https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/download/0.4.2/cassandra-datasource-0.4.2.tar.gz -O - | tar xz -C /var/lib/grafana/plugins


