FROM grafana/grafana:7.3.6

RUN wget -c https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/download/0.5.0/cassandra-datasource-0.5.0.tar.gz -O - | tar xz -C /var/lib/grafana/plugins
