version: '3'
services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
    volumes:
      - /var/lib/grafana
  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
  sample-data:
    image: cassandra:4
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/sample_data.sh"]
    volumes:
      - ./sample_data.sh:/sample_data.sh
