version: '3'
services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
    volumes:
      - /var/lib/grafana
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: "true"
    volumes:
      - /var/lib/cassandra
      - ../cassandra-entrypoint.sh:/docker-entrypoint.sh
      - ../test_data.cql:/test_data.cql
