version: '3'
services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
      GF_DEFAULT_APP_MODE: development
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
  sample-data:
    image: cassandra:4
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/sample_data.sh"]
    volumes:
      - ./sample_data.sh:/sample_data.sh
