name: Run tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: yarn install
        run: make fe-deps
      - name: yarn build
        run: make fe-build
      - name: go mod vendor
        run: make be-deps
      - name: go build linux
        run: OS=linux ARCH=amd64 make be-build
      - name: backend tests
        run: make be-test
