name: Run tests
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: yarn install
        run: docker run --rm -v ${PWD}:/opt/gcds -w /opt/gcds node:14 yarn install
      - name: yarn build
        run: docker run --rm -v ${PWD}:/opt/gcds -w /opt/gcds node:14 yarn build
      - name: go mod vendor
        run: docker run --rm -v ${PWD}:/go/src/github.com/ha/gcp -w /go/src/github.com/ha/gcp/backend golang:1 go mod vendor
      - name: go build linux
        run: docker run --rm -v ${PWD}:/go/src/github.com/ha/gcp -w /go/src/github.com/ha/gcp/backend golang:1 go build -o ../dist/cassandra-plugin_linux_amd64 .
      - name: backend tests
        run: docker run --rm -v ${PWD}:/go/src/github.com/ha/gcp -w /go/src/github.com/ha/gcp/backend golang:1 go test .
