name: Pre-release Check

on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    name: Lint and unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:ci

  validate:
    name: Build and validate plugin
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/package-plugin@main # zizmor: ignore[unpinned-uses] provided by grafana
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          node-version: 22
          go-version: 1.25
